# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ashjgW76ZXHwHEpeqJSsxN_rs8_8agi
"""

import requests
from datatime import datetime

api_key = "93d45676532366cf29caa9642"
location = input("enter the city name")

complete_api_;inl="http://api.openweathermap.org/data/2.5/forecast?q={},cn&mode=json&APPID={}"
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("---------------------------**********----------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-----------------------------*********--------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

